### ISSUE TITLE
Telemetry Value Calculations

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#10]
It appears that there may be an issue with the math calculations or something similar w/ regard to the numerical telemetry values that are decoded.  After several passes now with excellent reception, there may be one accurate decode but others of equal reception quality produce values that deviate significantly from expected values.  Further, using the same reception, the decoder from DK3WN renders the telemetry within limits.  (Of course, I don't KNOW that the values in the DK3WN decoder are correct, but only offer the comparison as an illustration to help)  Finally, even though out of limits, the values in the linux decoder and Windows decoder will be exactly the same when processing the same downlink stream.   (Screen shots below do NOT reflect the same packet)

![screenshot from 2017-04-01 00-47-45](https://cloud.githubusercontent.com/assets/19886368/24575773/e6af6f2e-167c-11e7-97ef-1688228f02e8.png)

![win-decoder](https://cloud.githubusercontent.com/assets/19886368/24575785/10481ed0-167d-11e7-9675-83be693d3a49.png)

**Comment by jmason86** [comment]
Thanks for this... it is really strange. It doesn't happen on my machine locally when I run it (macOS). I'll have to try running it on Windows to see if I can debug. The logic for identifying and decoding a packet is pretty simple so hopefully there's just a silly mistake in there somewhere. Glad that the DK3WN decoder is out there now too!

**Comment by jmason86** [comment]
Posted a potential fix. Mike Rupprecht caught another issue that may relate to this (transposed values of 0xC0) but I'm still looking into that one.

**Comment by K4KDR** [comment]
Thanks for the update!  Pulled the latest files & replayed previously recorded audio w/ good packets.  Unfortunately, the app decoded & displayed values obviously out of the expected range.  The window where the decoder was run from displayed the following; hope it helps!:
```

Traceback (most recent call last):
  File "minxss_beacon_decoder.py", line 373, in run
    self.target(*args, **kwargs)
  File "minxss_beacon_decoder.py", line 143, in readPort
    selectedTelemetryDictionary = minxssParser.parsePacket(bufferData)
  File "/home/k4kdr/MinXSS_Beacon_Decoder/minxss_parser.py", line 35, in parsePacket
    selectedTelemetryDictionary['FlightModel'] = self.decodeFlightModel(minxssPacket[51])                                       # [Unitless]
IndexError: bytearray index out of range
```

**Comment by jmason86** [comment]
Ditto comment from another issue, just for completeness: 

Try the release 2d2887f (corresponding to release 1.0.2-beta). All the bad decoding has almost certainly been due to KISS special characters, which are now handled.

**Comment by jmason86** [comment]
Looks like the math is worked out properly now. Other issues still stand but this one can be closed.
