### ISSUE TITLE
Suggestion:  add logfile entry for data upload success/failure

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#14]
Obviously not a priority, but with the addition of semi-automated uploads of user-collected telemetry to your database, it would be nice if that action would create a log file entry so that the contributor could know if/when the upload occurred.  Thanks!

**Comment by jmason86** [comment]
Definitely a good one. In fact, I think I'll add something nice to the GUI itself as well.

**Comment by jmason86** [comment]
Done! Shows up in the log and the GUI.
