### ISSUE TITLE
White background w/ almost white text

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#15]
This has been an issue since day-1 for me but I had been manually editing ui_mainWindow.py as a work-around.  Also, it only affected the upper-left "IP Address" section.  However, now with the new layout in commit 06a81e6, I will need to ask for assistance.  The entire GUI is now a white background with text that is only slightly darker than white. (see screen shot below)

I am running Ubuntu 16.04, fully updated, with no special alterations or unusual hardware.  I would greatly appreciate direction on how I might correct the display of the app to run with the darker background that I'm sure is intended.  In fact, in a recent tweet from JA0CAW, I see that the dark background is displaying properly on his system.

Many thanks as always! 

![screenshot from 2017-04-25 21-56-27](https://cloud.githubusercontent.com/assets/19886368/25415085/7618dd3c-2a03-11e7-8583-8cd737432d39.png)

**Comment by K4KDR** [comment]
Update:  if run with sudo (i.e., root), the GUI displays with a dark background.  Not being terribly familiar with python, any help understanding why this happens would be appreciated and might help others.  

(Editorial comment:  unless root authority is required to run the app, many would probably prefer that root authority NOT be required to run the app)

Command run:   sudo python minxss_beacon_decoder.py

**Comment by jmason86** [comment]
Give e8a03b3 a try. I used Qt Designer to enforce custom dark color palette in each window instead of allowing it to inherit (which only seems to work on Mac for some reason).

**Comment by K4KDR** [comment]
No apparent change in GUI white background.  Info follows:

```
k4kdr@:~/MinXSS_Beacon_Decoder$ uname -a
Linux k4kdr-linux 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

k4kdr@:~/MinXSS_Beacon_Decoder$ python --version
Python 2.7.12

k4kdr@:~/MinXSS_Beacon_Decoder$ git show --oneline -s --pretty=format:"%h, %ar, %ad : %s"
e8a03b3, 18 minutes ago, Wed Apr 26 09:59:01 2017 -0600 : Enforced dark color palette throughout for all platforms

k4kdr@:~/MinXSS_Beacon_Decoder$ python minxss_beacon_decoder.py 
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
Traceback (most recent call last):
  File "minxss_beacon_decoder.py", line 499, in prepareToExit
    self.uploadData()
  File "minxss_beacon_decoder.py", line 486, in uploadData
    scp_upload.upload(self.bufferOutputBinaryFilename)
  File "/home/k4kdr/MinXSS_Beacon_Decoder/scp_upload.py", line 24, in upload
    scp.put(file, remote_path = directory)
  File "/usr/lib/python2.7/dist-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/usr/lib/python2.7/dist-packages/scp.py", line 238, in _send_files
    self._recv_confirm()
  File "/usr/lib/python2.7/dist-packages/scp.py", line 321, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: scp: Dropbox/minxss_dropbox/data/ham_data/: No such file or directory
```
![screenshot from 2017-04-26 12-13-15](https://cloud.githubusercontent.com/assets/19886368/25444831/7ef43da8-2a7a-11e7-95ff-ec88db164596.png)

**Comment by jmason86** [comment]
Try d128719, I used a different method for setting the background color.

**Comment by K4KDR** [comment]
Using commit 5a22838, a dark background now correctly appears in the GUI when run as a standard user!

```
k4kdr@:~/MinXSS_Beacon_Decoder$ python minxss_beacon_decoder.py 

```
... however, please note the side-effects:

-Options box:  "Saving to logfile" window is very low-contrast
-About tab:  some text in images is very low-contrast

![screenshot from 2017-04-26 15-57-38](https://cloud.githubusercontent.com/assets/19886368/25454314/0cb1ce8e-2a9a-11e7-98ab-eeeb882a68cc.png)

![screenshot from 2017-04-26 15-57-44](https://cloud.githubusercontent.com/assets/19886368/25454331/17a73fea-2a9a-11e7-972d-a6271101e35a.png)

![screenshot from 2017-04-26 15-57-49](https://cloud.githubusercontent.com/assets/19886368/25454343/203df4be-2a9a-11e7-97df-9297fb738a15.png)

**Comment by jmason86** [comment]
5189c6a has better contrast for those things. Looks right on my system but I won't close until you confirm. Thanks!

**Comment by K4KDR** [comment]
Using commit 5189c6a, I believe that all text is clearly readable.  There may be value in reviewing the following screen shots because if there is anything NOT visible on my machine, I would not know it.  Looks great!

![screenshot from 2017-04-26 19-55-41](https://cloud.githubusercontent.com/assets/19886368/25462093/bfede8dc-2aba-11e7-9395-68428d900bae.png)

![screenshot from 2017-04-26 19-55-51](https://cloud.githubusercontent.com/assets/19886368/25462099/cc6bf626-2aba-11e7-8ad3-f1518fe193d1.png)

![screenshot from 2017-04-26 19-56-01](https://cloud.githubusercontent.com/assets/19886368/25462109/d74cd92a-2aba-11e7-9b2a-6c6b16eeae38.png)

**Comment by jmason86** [comment]
Looks great! More layout improvements on the way and some new minor features. Closing issue.
