### ISSUE TITLE
"Closing ground station link" after out-of-range data received

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#2]
Using Latest commit 9190210, similar to previous issue report.  However, it appears that in-range telemetry allows the app to continue to keep the TCP connection open.   Bad data, however, closes the link.  This was confirmed by testing repeatedly with two different packets received during the 0441utc pass 14-Mar-2017.    Error feedback in terminal was:
<hr>
Traceback (most recent call last):
  File "minxss_beacon_decoder.py", line 301, in run
    self.target(*args, **kwargs)
  File "minxss_beacon_decoder.py", line 214, in readSerial
    elif selectedTelemetryDictionary['BatteryTemperature'] >= 2.0 and selectedTelemetryDictionary['BatteryTemperatre'] < 5.0 or selectedTelemetryDictionary['BatteryTemperature'] > 25.0:
KeyError: 'BatteryTemperatre'
<hr>

**Comment by jmason86** [comment]
That same typo! I thought I'd caught it everywhere. It's been fixed. This is what happens when autocomplete doesn't work for strings :) Newest version has been fixed.
