### ISSUE TITLE
minxss_beacon_decoder.py KISS byte handling?

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#21]
Question ref. minxss_beacon_decoder.py file, line 239.

It is stated correctly that the KISS formatted file that many of us would be using as input to this decoder requires special handling of the "C0" and "DB" hex bytes.  

However, should the following section of line 239:

bytearray([0xdd]

... more accurately be:

bytearray([0xdb]

???

**Comment by K4KDR** [comment]
#22

**Comment by jmason86** [comment]
Yep! Merged pull request. Thanks for catching that!
