### ISSUE TITLE
GUI Version #'s ?

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#24]
Perhaps not immediately if many changes are being made per day, but at some point it might be helpful to update the application GUI "version" number as displayed on the main tab so that there is no confusion when screen shots are shared as to what version of the software is being run.

**Comment by jmason86** [comment]
I think I could make this work. Right now that is static and defined in Qt Creator. But I could make it accessible to the python code and update then update the number based on... something. 

I should be working in a separate branch for all of the changes the last week or so and then only merge it back into main and update the version number in the GUI at that time. I just finished cleaning the primary file so, after resolving other issues in it, I think I will do that.

**Comment by jmason86** [comment]
Sweet. And with the most recent commit 999841006081d5281296e3b70f4c42d7b36c755e I updated the GUi to v2.0.2. I'll try to stay on top of that.
