### ISSUE TITLE
22-Mar-2017 major increase in packets transmitted

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#4]
Not an "issue", but I wanted to pass along that there was a dramatic shift in the telemetry transmit cycle from MinXSS-1 at 0820 UTC 22-Mar-2017.  The spacecraft had previously been making one transmission every 55 seconds or so.  This morning, in a 3 minute period, I decoded 134 packets!  If anyone would like the audio for testing, it is at:  https://www.dropbox.com/s/1q9i8002vvke013/2017-03-22--0820--MinXSS-1-HDSDR-replay-audacity-crop.wav?dl=0

**Comment by jmason86** [comment]
You likely caught the tail end of our high-data rate downlink after a commanded pass over Boulder. I'm closing the ticket as not an issue but it'll still be viewable and linkable.
