### ISSUE TITLE
Application screen resize

### ISSUE THREAD

**Issue by janvgils** [jmason86/MinXSS_Beacon_Decoder#6]
Hi,

I am testing the application on a Laptop with a 1600x900 screen size and I can't make the program fit on my screen and am unable to see the bottom part - Raw Serial data (hex):

**Comment by jmason86** [comment]
Noted. I'll look into how to get Qt applications to do intelligent rescaling. I'd like to avoid putting a scroll bar in the app if possible so that everything can be seen at once.

**Comment by jmason86** [comment]
The newest commit (c0ceb1c) has resized the window to be smaller (minimum size 900 x 670) and separated content into tabs. Let me know if that works better. By default I have the hex stuff hidden at the bottom but if you expand the window down you'll be able to see it.

**Comment by K4KDR** [comment]
Excellent!  Just a great improvement - fine job!

I understand that everyone's screen size & resolution is different, but in
my case the laptop screen was not able to display the full GUI window
properly.  Now all is well.

Thank you!


==========================

**Comment by jmason86** [comment]
Awesome! This layout makes a lot more sense too because you don't need to see all that static information like IP address all the time. Closing the issue.
