### ISSUE TITLE
'connect_port_get_packet' is not defined

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#8]
In commit 72b2df8, when the "Connect" button is clicked, no TCP connection is made to the software modem on the specified port.  In the terminal window where minxss_beacon_decoder.py was launched, the following is logged:

```
  File "minxss_beacon_decoder.py", line 83, in connectClicked
    connectedPort = connect_port_get_packet.connect_socket(ipAddress, port, self.log)
NameError: global name 'connect_port_get_packet' is not defined
```

**Comment by jmason86** [comment]
Whoops! That's because I forgot to uncomment the import statement for connect_port_get_packet after I was debugging the pyinstaller stuff (to create executables). New commit up with this line uncommented.
