### ISSUE TITLE
Windows binary - comments

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#9]
I don't know if my experience is universal or unique to my Windows installation, but I wanted to pass along the following observations regarding use of the new Windows executable.

-using previously recorded data, works great!

-was unable to establish a TCP connection to the software modem until copying "MinXSS_Beacon_DecoderWin.exe" and "input_properties.cfg" to the 'C:\users\{username}\MinXSS_Beacon_Decoder' folder (which had been auto-created by the app when first run from the download location.  

-for the app to show the images, the "assets" folder also had to be copied to the 'C:\users\{username}\MinXSS_Beacon_Decoder' folder.

... if my file location observations are accurate, it would be helpful to others to include that in an install readme.

Lastly, for all operating systems, it would add clarity for the end-user if the IP Address & Port of the software modem were configured in the GUI -or- from a separate .config file, but not both.  It would be great if the GUI 'reflected' the settings from a .config file, but it creates confusion if there is more than one way to adjust settings like these.

Great job!

**Comment by jmason86** [comment]
This is great info! Thanks K4KDR! I'm going to include this in the README for greater visibility and in the notes for the first release of the code.

**Comment by jmason86** [comment]
Agreed on the last point though too... it should already be working the way you describe but maybe something's being dropped. The code right now is supposed to read that config file on launch and set those values as the default. If you change then in the app and hit connect, the config file gets updated. The idea was that you set it once and as long as your setup doesn't change, you don't have to keep tying in the stuff anymore.. you can just open the app and hit connect.
